# Generated by Django 5.1.6 on 2025-03-05 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField(help_text='Номер стола, например: 1, 2, 3...')),
                ('items', models.JSONField(help_text='Список заказанных блюд с ценами, например: [{"position": "Картофель фри", "price": 199.99}, {"position": "Шашлык", "price": 454.99}, ...]')),
                ('total_price', models.FloatField(default=0.0, help_text='Общая стоимость заказа, которая вычисляется автоматически.Чтобы избежать ошибок, если поле не будет заполнено, устанавливаем дефолтное значение')),
                ('status', models.CharField(help_text='Статус заказа: “в ожидании”, “готово”, “оплачено”', max_length=50)),
            ],
        ),
    ]
