# Generated by Django 5.1.6 on 2025-03-05 09:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_system_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='table_number',
            field=models.IntegerField(help_text='Номер стола, например: 1, 2, 3...', validators=[django.core.validators.MinValueValidator(1, message='Номер стола должен быть больше 0.')]),
        ),
    ]
