# Generated by Django 5.1.6 on 2025-03-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_system_app', '0002_alter_order_table_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.JSONField(default='{"position": "Картофель фри", "price": 199.99}', help_text='Список заказанных блюд с ценами, например: [{"position": "Картофель фри", "price": 199.99}, {"position": "Шашлык", "price": 454.99}, ...]'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='в ожидании', help_text='Статус заказа: “в ожидании”, “готово”, “оплачено”', max_length=50),
        ),
    ]
