# Generated by Django 5.1.6 on 2025-03-05 09:33

import management_system_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_system_app', '0005_alter_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.JSONField(default=management_system_app.models.default_items, help_text='Список заказанных блюд с ценами, например: [{"position": "Картофель фри", "price": 199.99}, {"position": "Шашлык", "price": 454.99}, ...]'),
        ),
    ]
