# Generated by Django 5.1.6 on 2025-03-07 11:10

import management_system_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_system_app', '0007_alter_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.JSONField(default=management_system_app.models.default_items, help_text='Список заказанных блюд с ценами, например: [{"position": "Картофель фри", "price": 199.99}, {"position": "Шашлык", "price": 454.99}, ...] Обратите внимание, что кавычки должны быть двойными'),
        ),
    ]
